{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.test_module",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6268720,
          "sha512": "e54840667b3eddbb59b2a59037cb216d51f5b16721ca02ab1ff768351141f5651c9356e4f04bc8dc8d9a4f77191b9e30b8108c464138f71a45709e10fe094ff0",
          "sha256": "76be62b0396317f07269d63b52c041eabd0a91161aae2197921fe7359531df7c",
          "sha1": "396f488332ce80066fb09ef4bf5936e15c12da4d",
          "md5": "ff5c8cd0ad1716481a10882122dee6eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6268720,
          "sha512": "e54840667b3eddbb59b2a59037cb216d51f5b16721ca02ab1ff768351141f5651c9356e4f04bc8dc8d9a4f77191b9e30b8108c464138f71a45709e10fe094ff0",
          "sha256": "76be62b0396317f07269d63b52c041eabd0a91161aae2197921fe7359531df7c",
          "sha1": "396f488332ce80066fb09ef4bf5936e15c12da4d",
          "md5": "ff5c8cd0ad1716481a10882122dee6eb"
        }
      ]
    }
  ]
}
